package com.ecommerce.user.model;

import com.ecommerce.user.dto.UserRole;

import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Data //Getters and Setters (Need to access the data)
@Document(collection = "users") //Mongodb Document (collection name = "users")
public class User {

    //These data will be stored as JSON in mongodb
    @Id
    private String id;
    //Why ID is String in MongoDB
    //each user will have a object name, and it will stored in string
    //That will be autogenerated, we will be using that.

    private String firstName;
    private String lastName;

    //Index helps faster searching
    //Index is unique
    @Indexed(unique = true)
    private String email;
    private String phone;
    private UserRole role = UserRole.CUSTOMER; //enum (Default = CUSTOMER)


    // private Address address;
    // This will be stored inside the User JSON as another JSON
    private Address address;


    @CreatedDate
    private LocalDateTime createdAt;

    @LastModifiedDate
    private LocalDateTime updatedAt;




}
