spring.application.name=configserver
server.port=8888



#Activate native profile -> Use local file system (if this is GIT, it will use GIT)
spring.profiles.active=native

#Whare to locate those files (classpath -> will not update in the runtime)
#spring.cloud.config.server.native.search-locations=classpath:/config

#Whare to locate those files (Add the entire location)
spring.cloud.config.server.native.search-locations=file:///D:\Spring\Spring_Microservices\configserver\src\main\resources\config

  #----------RabbitMQ setup---------
#URL to talk to the rabbitmq
spring.rabbitmq.host=localhost
#Port (Expose the port which communicate with the docker instance)
spring.rabbitmq.port=5672
#default usernames and passwords
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#Expose the endpoint (actuator) -> Expose all
management.endpoints.web.exposure.include=*
#Or u can expose a specific endpoint
#management.endpoints.web.exposure.include="busrefresh"


